<?php

/**
 * Implements hook_watchdog().
 * Redirects watchdog() calls to a log file. To configure the log file to which
 * logs will be written add the following configuration in settings.php
 *
 *   $conf['nice_logger_file'] = 'YOUR_OUTPUT_FILE'
 */
function nice_logger_watchdog($log_entry) {
  $log_file = variable_get('nice_logger_file', 'log/application.log');
  $min_level = variable_get('nice_logger_level', WATCHDOG_DEBUG);
  $rollbar_enabled = class_exists('Rollbar');
  $logger = new NiceLogger($log_file, $min_level, $rollbar_enabled);
  $logger->log($log_entry);
}

/**
 * Implements hook_boot().
 * Loads Rollbar library and sets default error handlers.
 */
function nice_logger_boot() {
  if ($rollbar_token = variable_get('nice_logger_rollbar_token')) {
    require_once "sites/all/libraries/rollbar/src/rollbar.php";
    Rollbar::init([
      'access_token' => $rollbar_token,
      'environment' => variable_get('nice_logger_rollbar_environment', 'development')
    ]);
  }
}
